-- Reference data: regions, MRCs (health facilities) and villages.
-- Source: "mrctarget villages" sheet of the data dictionary + the 26-site list.
-- Only MRCs with active = true appear on the dashboard.

create table public.region (
  regioncode integer primary key,
  regionname text not null
);

create table public.mrc (
  mrccode integer primary key,
  mrcname text not null,          -- name as used in the survey app, e.g. "Bala HCIII"
  short_name text not null,       -- name used on the dashboard, e.g. "Bala"
  district text,
  regioncode integer references public.region,
  target_hh integer,              -- target number of households; fill in manually
  active boolean not null default false
);

create table public.village (
  mrccode integer not null references public.mrc,
  villagecode integer not null,
  villagename text not null,
  primary key (mrccode, villagecode)
);

insert into public.region (regioncode, regionname) values
  (1, 'Busoga'),
  (2, 'Bukedi'),
  (4, 'Teso'),
  (5, 'Karamoja'),
  (6, 'Lango'),
  (7, 'Acholi'),
  (8, 'West Nile'),
  (9, 'Bunyoro'),
  (10, 'Tooro'),
  (11, 'Kigezi'),
  (14, 'North Buganda');

insert into public.mrc (mrccode, mrcname, short_name, district, regioncode, active) values
  (1, 'Kasambya HCIII', 'Kasambya HCIII', null, 14, false),
  (9, 'Kigorobya HCIV', 'Kigorobya HCIV', null, 9, false),
  (12, 'Kyatiri HCIII', 'Kyatiri', 'Masindi', 9, true),
  (14, 'Diima HCIII', 'Diima', 'Kiryandongo', 9, true),
  (15, 'Opia HCIII', 'Opia HCIII', null, 8, false),
  (18, 'Ayipe HCIII', 'Ayipe HCIII', null, 8, false),
  (19, 'Metu HCIII', 'Metu HCIII', null, 8, false),
  (21, 'Koch Goma HCIV', 'Koch Goma', 'Nwoya', 7, true),
  (23, 'Atiak HCIV', 'Atiak', 'Amuru', 7, true),
  (25, 'Awach HCIV', 'Awach', 'Gulu', 7, true),
  (27, 'Lalogi HCIV', 'Lalogi', 'Omoro', 7, true),
  (29, 'Padibe HCIII', 'Padibe', 'Lamwo', 7, true),
  (31, 'Namokora HCIV', 'Namokora', 'Kitgum', 7, true),
  (32, 'Kitgum Matidi HCIII', 'Kitgum Matidi', 'Kitgum', 7, true),
  (33, 'Patongo HCIII', 'Patongo', 'Agago', 7, true),
  (36, 'Otwal HCIII', 'Otwal', 'Oyam', 6, true),
  (37, 'Aboke HCIV', 'Aboke', 'Kole', 6, true),
  (38, 'Bala HCIII', 'Bala', 'Kole', 6, true),
  (40, 'Akokoro HCIII', 'Akokoro', 'Apac', 6, true),
  (41, 'Aduku HCIV', 'Aduku', 'Kwania', 6, true),
  (42, 'Apwori HCIII', 'Apwori', 'Apac', 6, true),
  (43, 'Lokolia HCIV', 'Lokolia', 'Kaabong', 5, true),
  (47, 'Morungatuny HCIII', 'Morungatuny', 'Amuria', 4, true),
  (56, 'Nawaikoke HCIII', 'Nawaikoke HCIII', 'Kaliro', 1, true),
  (59, 'Budondo HCIV', 'Budondo HCIV', 'Jinja', 1, true),
  (61, 'Buwaiswa HCIV', 'Buwaiswa', 'Kamuli', 1, true),
  (62, 'Kigandalo HCIV', 'Kigandalo', 'Mayuge', 1, true),
  (64, 'Busitema HCIII', 'Busitema', 'Busia', 2, true),
  (65, 'Kihihi HCIV', 'Kihihi HCIV', null, 11, false),
  (66, 'Amolatar HCIV', 'Amolatar HCIV', 'Amolatar', 6, true),
  (69, 'Orum HCIV', 'Orum HCIV', 'Otuke', 6, true),
  (70, 'Nagongera HCIV', 'Nagongera HCIV', null, 2, false),
  (71, 'Nadunget HC III', 'Nadunget', 'Moroto', 5, true),
  (72, 'Kamwezi HC IV', 'Kamwezi HC IV', null, 11, false),
  (73, 'Muko HC IV', 'Muko HC IV', null, 11, false),
  (74, 'Chahafi HC IV', 'Chahafi HC IV', null, 11, false),
  (75, 'Maziba HC IV', 'Maziba HC IV', null, 11, false),
  (77, 'Karambi HC IV', 'Karambi HC IV', null, 10, false),
  (78, 'Rubondo HC II', 'Rubondo HC II', null, 11, false),
  (79, 'Rwenyawawa HC III', 'Rwenyawawa HC III', null, 9, false),
  (80, 'Panyadoli HC IV', 'Panyadoli HC IV', null, 9, false),
  (81, 'Palorinya HC III', 'Palorinya HC III', null, 8, false);

insert into public.village (mrccode, villagecode, villagename) values
  (56, 1, 'NAWAIKOKE'),
  (56, 2, 'KAJUBU'),
  (56, 3, 'LUKUMI'),
  (56, 4, 'BUKUNYA'),
  (59, 2, 'NAMIZI CENTRAL'),
  (61, 1, 'BUWAISWA'),
  (61, 2, 'NAMADHI'),
  (61, 3, 'NAKATE'),
  (62, 1, 'KIGANDALO A'),
  (62, 2, 'KIGANDALO B'),
  (62, 3, 'BUGONDO'),
  (64, 1, 'SYANYONJA'),
  (64, 2, 'NAMUKOMBE'),
  (64, 3, 'NAMBEWO'),
  (70, 1, 'TAWO JWOK'),
  (70, 2, 'MAHANGA'),
  (70, 3, 'AWANYA'),
  (47, 1, 'AKUYA'),
  (47, 2, 'OJINGAI'),
  (47, 3, 'OMUNYIR'),
  (47, 4, 'ATEUSO'),
  (43, 1, 'LOKOLIA CENTRE'),
  (43, 2, 'KALODEKE'),
  (43, 3, 'NAPETABUL'),
  (71, 1, 'Nakapelimen Cell'),
  (71, 2, 'Lolain Cell'),
  (71, 3, 'Lokilala'),
  (71, 4, 'Lokorirot Cell'),
  (71, 5, 'Nachuka Cell'),
  (36, 1, 'TE - YAO'),
  (36, 2, 'ALEGE'),
  (36, 3, 'OGUK'),
  (36, 4, 'OTWAL TRADING CENTRE ''A'''),
  (37, 1, 'ARAO'),
  (37, 2, 'ACUNGU LYEC ''A'''),
  (37, 3, 'ATEK'),
  (38, 1, 'TECAMBIA MAIN'),
  (38, 2, 'OLIL'),
  (38, 3, 'OLAI'),
  (40, 1, 'TETUGO'),
  (40, 2, 'KAYEI'),
  (40, 3, 'WANGCENYE'),
  (40, 4, 'AKOKORO T/C'),
  (40, 5, 'ABYEIBUTI'),
  (41, 1, 'Akaidebe'),
  (41, 2, 'Olami ''B'''),
  (41, 3, 'Olami ''A'''),
  (42, 1, 'APWORI'),
  (42, 2, 'OYIKOWANGE'),
  (42, 3, 'WI GWENG A'),
  (42, 4, 'WI GWENG B'),
  (42, 5, 'AYAT'),
  (42, 6, 'OMULE'),
  (66, 2, 'AMOLATAR HEADQUARTERS ''B'''),
  (66, 5, 'ORIMAI'),
  (69, 1, 'BARODUGU'),
  (69, 2, 'ADWONG IBUTO'),
  (69, 3, 'ADWIRPIDA'),
  (69, 4, 'TEBOKE'),
  (69, 5, 'AKAIDEBE'),
  (21, 1, 'Kal ''B'''),
  (21, 2, 'Kal ''A1'''),
  (21, 3, 'Kal ''A2'''),
  (23, 1, 'Kal East'),
  (25, 1, 'Payuta'),
  (27, 1, 'OPWAC'),
  (29, 1, 'ATWOL A'),
  (29, 2, 'ATWOL B'),
  (29, 3, 'LOTIBOL'),
  (29, 4, 'MISSION'),
  (29, 5, 'ANYIBI'),
  (31, 1, 'MISSION'),
  (31, 2, 'ORYANG CENTRAL'),
  (31, 3, 'PAGER'),
  (31, 4, 'PUNU AKURU'),
  (31, 5, 'TWONU OKON'),
  (32, 1, 'BOBI CENTRAL'),
  (32, 2, 'PAGWA AWERE'),
  (33, 1, 'COUNTY HQTRS'),
  (33, 2, 'OPOROT NORTH'),
  (33, 3, 'BARDEGE'),
  (33, 4, 'OPOROT CENTRAL'),
  (15, 1, 'Opia Centre'),
  (15, 2, 'Ewavuni'),
  (15, 3, 'Kongodo'),
  (15, 4, 'Yivu'),
  (15, 5, 'Doli'),
  (18, 1, 'KITIMIRI'),
  (18, 2, 'AGMBARU'),
  (18, 3, 'BALALA'),
  (19, 1, 'METU T/C'),
  (19, 2, 'PAMENYUA'),
  (19, 3, 'INDRI'),
  (19, 4, 'GWERE MONDI'),
  (19, 5, 'GWERE LUZIRA'),
  (19, 6, 'CECELOGO'),
  (81, 1, 'UKUNI WEST'),
  (81, 2, 'BUDARI'),
  (81, 3, 'PASU'),
  (9, 1, 'KIRYANDONGO'),
  (9, 2, 'KIGOROBYA I'),
  (9, 3, 'KIGOROBYA II'),
  (9, 4, 'KIKWANANA'),
  (9, 5, 'KIKONKONA'),
  (12, 1, 'KYATIRI CENTRE'),
  (12, 5, 'KYAMBOGO'),
  (12, 6, 'KYABAKAMI'),
  (14, 1, 'PII-AKEYO'),
  (14, 2, 'DIIMA A'),
  (14, 3, 'DIIMA B'),
  (14, 4, 'ALENGO'),
  (79, 1, 'RWENYAWAWA'),
  (79, 2, 'NYAMPINDU'),
  (80, 1, 'CLUSTER K'),
  (80, 2, 'CLUSTER N'),
  (77, 1, 'KARAMBI'),
  (77, 2, 'KYASENDA I'),
  (77, 3, 'KYASENDA II'),
  (77, 4, 'MIRAMI I'),
  (77, 5, 'MIRAMI II'),
  (65, 1, 'MARKET CELL'),
  (65, 2, 'CENTRAL KIHIIHI'),
  (65, 3, 'RUTWE'),
  (65, 4, 'NDEEBA'),
  (72, 1, 'KABIRIZI'),
  (72, 2, 'KAMUHA'),
  (72, 3, 'KAGARAMA'),
  (72, 4, 'MUTOJO'),
  (73, 1, 'KAMUSERWA'),
  (73, 2, 'KANYAMATEMBE'),
  (73, 3, 'KATASYA'),
  (73, 4, 'RUTOGA'),
  (73, 5, 'BICERERE'),
  (73, 6, 'RUSHAMBYA'),
  (73, 7, 'RUSHUNGA'),
  (73, 8, 'RWAMABARE'),
  (74, 1, 'KABAMI'),
  (74, 2, 'GISHA'),
  (74, 3, 'NYABUNE'),
  (75, 1, 'BIRAMBO'),
  (75, 2, 'EIZINIRO'),
  (75, 3, 'KAMURONKO'),
  (75, 4, 'KANONI'),
  (75, 5, 'NYAKARAMBI'),
  (75, 6, 'OMUKASHENYI'),
  (75, 7, 'RWEMIHANGA'),
  (75, 8, 'KASIRIMA'),
  (78, 1, 'KISUURA'),
  (78, 2, 'KISUURA B'),
  (78, 3, 'KISUURA C'),
  (1, 1, 'KASAMBYA A'),
  (1, 2, 'KASAMBYA CENTRAL'),
  (1, 3, 'KIMWANYI A');
